name: Nightly Build

on:
  schedule:
    # cronjob that triggers every day at 2PM UTC
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  update_lists:
    runs-on: ubuntu-latest
    name: Update blocklists
    steps:
      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
