name: Update blocklists

on:
  schedule:
    # cronjob that triggers every day at 2PM UTC
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  update_lists:
    runs-on: ubuntu-latest
    name: Update blocklists
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Build generator
        run: |
          cd generator
          go build
