name: Update blocklists

on:
  schedule:
    # cronjob that triggers every hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update_lists:
    runs-on: ubuntu-latest
    name: Update blocklists
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build generator
        run: |
          cd generator
          go build .

      - name: Generate blocklists
        run: |
          mkdir -p lists
          cd generator
          ./privacy_firewall

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "lists"
          default_author: github_actions
          message: "feat: auto update blocklists"
