name: Update blocklists

on:
  schedule:
    # cronjob that triggers every hour
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update_lists:
    runs-on: ubuntu-latest
    name: Update blocklists
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache generator
        id: cache-generator
        uses: actions/cache@v2
        with:
          path: generator/privacy_firewall
          key: ${{ runner.os }}-generator-${{ hashFiles('./generator/*') }}

      - if: steps.cache-generator.outputs.cache-hit != 'true'
        name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - if: steps.cache-generator.outputs.cache-hit != 'true'
        name: Build generator
        run: |
          cd generator
          go build .

      - name: Generate blocklists
        run: |
          mkdir -p lists
          cd generator
          ./privacy_firewall

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "lists"
          default_author: github_actions
          message: "feat: auto update blocklists"
